/**
 * 旧前端实际使用的 API 端点清单
 * 来源: cloudManagement-old/src/util/request.ts
 *
 * 网关前缀 /api 由 vite proxy 剥离，后端路由从 /sys-app、/iot-app 等开始。
 */

export const API = {
  sys: {
    captcha: 'GET /sys-app/common/captcha64',
    login: 'POST /sys-app/login',
    logout: 'POST /sys-app/logout',
    menu: 'POST /sys-app/sys_menu/menu',
    roleMenu: 'POST /sys-app/role/roleMenu',
    rolePage: 'POST /sys-app/role/_page',
    roleList: 'POST /sys-app/role/list',
    roleDelete: 'GET /sys-app/role/_delete',
    roleSave: 'POST /sys-app/role/_save_or_update',
    menuPermission: 'POST /sys-app/role/menuPermission',
    userPermission: 'POST /sys-app/role/userPermission',
    rolePermissionBatch: 'POST /sys-app/role_permission/batchChangePermission',
    rolePermissionSaveBatch: 'POST /sys-app/role_permission/_save_or_update_batch',
    roleMenuSaveBatch: 'POST /sys-app/role_menu/_save_or_update_batch',
    userPage: 'POST /sys-app/sys_user/_page',
    userSearchAll: 'POST /sys-app/sys_user/_search_all',
    userSave: 'POST /sys-app/sys_user/_save_or_update',
    userSaveBatch: 'POST /sys-app/sys_user/_save_or_update_batch',
    userDelete: 'GET /sys-app/sys_user/_delete',
    dimensionTree: 'POST /sys-app/sys-dimension/tree',
    dimensionSearchOne: 'POST /sys-app/sys-dimension/_search_one',
    dimensionSave: 'POST /sys-app/sys-dimension/_save_or_update',
    dimensionDelete: 'GET /sys-app/sys-dimension/_delete',
    auditLogPage: 'POST /sys-app/audit_log/_page',
    auditLogDeleteBatch: 'POST /sys-app/audit_log/_delete_batch',
  },
  iot: {
    unit: 'GET /iot-app/configuration/unit',
    deviceSearchOne: 'POST /iot-app/device/_search_one',
    devicePage: 'POST /iot-app/device/_page',
    deviceSave: 'POST /iot-app/device/_save_or_update',
    deviceSaveBatch: 'POST /iot-app/device/_save_or_update_batch',
    deviceDelete: 'GET /iot-app/device/_delete',
    deviceSync: 'GET /iot-app/device/_sync',
    deviceRuleParse: 'POST /iot-app/device/_rule_parse',
    deviceRuleUpdate: 'POST /iot-app/device/_rule_update',
    productParse: 'POST /iot-app/product/_parse',
    productSerialize: 'POST /iot-app/product/_serialize',
    productPage: 'POST /iot-app/product/_page',
    productSearchOne: 'POST /iot-app/product/_search_one',
    productSave: 'POST /iot-app/product/_save_or_update',
    productDelete: 'GET /iot-app/product/_delete',
    networkPage: 'POST /iot-app/network/_page',
    networkSave: 'POST /iot-app/network/_save_or_update',
    networkDelete: 'GET /iot-app/network/_delete',
    networkUpload: 'POST /iot-app/network/_upload',
    gatewayPage: 'POST /iot-app/gateway/_page',
    gatewaySave: 'POST /iot-app/gateway/_save_or_update',
    gatewayDelete: 'GET /iot-app/gateway/_delete',
    protocolPage: 'POST /iot-app/protocol/_page',
    protocolUpload: 'POST /iot-app/protocol/_upload',
    protocolSave: 'POST /iot-app/protocol/_save_or_update',
    protocolReload: 'GET /iot-app/protocol/_reload',
    protocolDelete: 'GET /iot-app/protocol/_delete',
    protocolTest: 'POST /iot-app/protocol/_test',
    /** 旧前端仍调用，后端可能已迁移至 device metadata.rules */
    rulePage: 'POST /iot-app/rule/_page',
    ruleSave: 'POST /iot-app/rule/save',
    ruleDelete: 'GET /iot-app/rule/_delete',
  },
  notify: {
    configPage: 'POST /notify-app/notify-config/_page',
    configSupport: 'GET /notify-app/notify-config/support',
    configSearchOne: 'POST /notify-app/notify-config/_search_one',
    configSave: 'POST /notify-app/notify-config/_save_or_update',
    configDelete: 'GET /notify-app/notify-config/_delete',
    contentModel: 'GET /notify-app/notify-config/contentModel',
    templatePage: 'POST /notify-app/notify-template/_page',
    templateSearchOne: 'POST /notify-app/notify-template/_search_one',
    templateContent: 'POST /notify-app/notify-template/templateContent',
    templateSave: 'POST /notify-app/notify-template/_save_or_update',
    templateDelete: 'GET /notify-app/notify-template/_delete',
    templateSendTest: 'POST /notify-app/notify-template/send_test',
    /** 旧前端仍调用，后端 controller 可能缺失 */
    templateUserPage: 'POST /notify-app/notify-template-user/_page',
    templateUserSave: 'POST /notify-app/notify-template-user/_save_or_update',
    templateUserDelete: 'GET /notify-app/notify-template-user/_delete',
  },
  register: {
    propertyPage: 'POST /register-app/timeseries/property/_page',
    propertyHistory: 'GET /register-app/timeseries/property/history',
    logPage: 'POST /register-app/timeseries/log/_page',
    functionPage: 'POST /register-app/timeseries/function/_page',
    alarmPage: 'POST /register-app/timeseries/alarm/_page',
    boardPage: 'POST /register-app/timeseries/board/_page',
    socket: '/register-app/socket',
  },
  user: {
    productSync: 'GET /user-app/product/_synchronous',
  },
} as const
