/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSystemUsersRouteImport } from './routes/_app.system.users'
import { Route as AppSystemRolesRouteImport } from './routes/_app.system.roles'
import { Route as AppSystemOrgsRouteImport } from './routes/_app.system.orgs'
import { Route as AppNotifTemplatesRouteImport } from './routes/_app.notif.templates'
import { Route as AppNotifConfigsRouteImport } from './routes/_app.notif.configs'
import { Route as AppIngestProtocolsRouteImport } from './routes/_app.ingest.protocols'
import { Route as AppIngestGatewaysRouteImport } from './routes/_app.ingest.gateways'
import { Route as AppIngestComponentsRouteImport } from './routes/_app.ingest.components'
import { Route as AppDevicesProductsRouteImport } from './routes/_app.devices.products'
import { Route as AppDevicesListRouteImport } from './routes/_app.devices.list'
import { Route as AppDevicesProductsIndexRouteImport } from './routes/_app.devices.products.index'
import { Route as AppDevicesProductsIdRouteImport } from './routes/_app.devices.products.$id'
import { Route as AppDevicesListIndexRouteImport } from './routes/_app.devices.list.index'
import { Route as AppDevicesListIdRouteImport } from './routes/_app.devices.list.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemUsersRoute = AppSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRolesRoute = AppSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemOrgsRoute = AppSystemOrgsRouteImport.update({
  id: '/system/orgs',
  path: '/system/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifTemplatesRoute = AppNotifTemplatesRouteImport.update({
  id: '/notif/templates',
  path: '/notif/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifConfigsRoute = AppNotifConfigsRouteImport.update({
  id: '/notif/configs',
  path: '/notif/configs',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestProtocolsRoute = AppIngestProtocolsRouteImport.update({
  id: '/ingest/protocols',
  path: '/ingest/protocols',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestGatewaysRoute = AppIngestGatewaysRouteImport.update({
  id: '/ingest/gateways',
  path: '/ingest/gateways',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestComponentsRoute = AppIngestComponentsRouteImport.update({
  id: '/ingest/components',
  path: '/ingest/components',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesProductsRoute = AppDevicesProductsRouteImport.update({
  id: '/devices/products',
  path: '/devices/products',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesListRoute = AppDevicesListRouteImport.update({
  id: '/devices/list',
  path: '/devices/list',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesProductsIndexRoute = AppDevicesProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevicesProductsRoute,
} as any)
const AppDevicesProductsIdRoute = AppDevicesProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDevicesProductsRoute,
} as any)
const AppDevicesListIndexRoute = AppDevicesListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevicesListRoute,
} as any)
const AppDevicesListIdRoute = AppDevicesListIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDevicesListRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/devices/list': typeof AppDevicesListRouteWithChildren
  '/devices/products': typeof AppDevicesProductsRouteWithChildren
  '/ingest/components': typeof AppIngestComponentsRoute
  '/ingest/gateways': typeof AppIngestGatewaysRoute
  '/ingest/protocols': typeof AppIngestProtocolsRoute
  '/notif/configs': typeof AppNotifConfigsRoute
  '/notif/templates': typeof AppNotifTemplatesRoute
  '/system/orgs': typeof AppSystemOrgsRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/devices/list/$id': typeof AppDevicesListIdRoute
  '/devices/list/': typeof AppDevicesListIndexRoute
  '/devices/products/$id': typeof AppDevicesProductsIdRoute
  '/devices/products/': typeof AppDevicesProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/devices/list': typeof AppDevicesListIndexRoute
  '/ingest/components': typeof AppIngestComponentsRoute
  '/ingest/gateways': typeof AppIngestGatewaysRoute
  '/ingest/protocols': typeof AppIngestProtocolsRoute
  '/notif/configs': typeof AppNotifConfigsRoute
  '/notif/templates': typeof AppNotifTemplatesRoute
  '/system/orgs': typeof AppSystemOrgsRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/devices/list/$id': typeof AppDevicesListIdRoute
  '/devices/products/$id': typeof AppDevicesProductsIdRoute
  '/devices/products': typeof AppDevicesProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/devices/list': typeof AppDevicesListRouteWithChildren
  '/_app/devices/products': typeof AppDevicesProductsRouteWithChildren
  '/_app/ingest/components': typeof AppIngestComponentsRoute
  '/_app/ingest/gateways': typeof AppIngestGatewaysRoute
  '/_app/ingest/protocols': typeof AppIngestProtocolsRoute
  '/_app/notif/configs': typeof AppNotifConfigsRoute
  '/_app/notif/templates': typeof AppNotifTemplatesRoute
  '/_app/system/orgs': typeof AppSystemOrgsRoute
  '/_app/system/roles': typeof AppSystemRolesRoute
  '/_app/system/users': typeof AppSystemUsersRoute
  '/_app/devices/list/$id': typeof AppDevicesListIdRoute
  '/_app/devices/list/': typeof AppDevicesListIndexRoute
  '/_app/devices/products/$id': typeof AppDevicesProductsIdRoute
  '/_app/devices/products/': typeof AppDevicesProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/devices/list'
    | '/devices/products'
    | '/ingest/components'
    | '/ingest/gateways'
    | '/ingest/protocols'
    | '/notif/configs'
    | '/notif/templates'
    | '/system/orgs'
    | '/system/roles'
    | '/system/users'
    | '/devices/list/$id'
    | '/devices/list/'
    | '/devices/products/$id'
    | '/devices/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/devices/list'
    | '/ingest/components'
    | '/ingest/gateways'
    | '/ingest/protocols'
    | '/notif/configs'
    | '/notif/templates'
    | '/system/orgs'
    | '/system/roles'
    | '/system/users'
    | '/devices/list/$id'
    | '/devices/products/$id'
    | '/devices/products'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/devices/list'
    | '/_app/devices/products'
    | '/_app/ingest/components'
    | '/_app/ingest/gateways'
    | '/_app/ingest/protocols'
    | '/_app/notif/configs'
    | '/_app/notif/templates'
    | '/_app/system/orgs'
    | '/_app/system/roles'
    | '/_app/system/users'
    | '/_app/devices/list/$id'
    | '/_app/devices/list/'
    | '/_app/devices/products/$id'
    | '/_app/devices/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/users': {
      id: '/_app/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AppSystemUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/roles': {
      id: '/_app/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AppSystemRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/orgs': {
      id: '/_app/system/orgs'
      path: '/system/orgs'
      fullPath: '/system/orgs'
      preLoaderRoute: typeof AppSystemOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notif/templates': {
      id: '/_app/notif/templates'
      path: '/notif/templates'
      fullPath: '/notif/templates'
      preLoaderRoute: typeof AppNotifTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notif/configs': {
      id: '/_app/notif/configs'
      path: '/notif/configs'
      fullPath: '/notif/configs'
      preLoaderRoute: typeof AppNotifConfigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest/protocols': {
      id: '/_app/ingest/protocols'
      path: '/ingest/protocols'
      fullPath: '/ingest/protocols'
      preLoaderRoute: typeof AppIngestProtocolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest/gateways': {
      id: '/_app/ingest/gateways'
      path: '/ingest/gateways'
      fullPath: '/ingest/gateways'
      preLoaderRoute: typeof AppIngestGatewaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest/components': {
      id: '/_app/ingest/components'
      path: '/ingest/components'
      fullPath: '/ingest/components'
      preLoaderRoute: typeof AppIngestComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/products': {
      id: '/_app/devices/products'
      path: '/devices/products'
      fullPath: '/devices/products'
      preLoaderRoute: typeof AppDevicesProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/list': {
      id: '/_app/devices/list'
      path: '/devices/list'
      fullPath: '/devices/list'
      preLoaderRoute: typeof AppDevicesListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/products/': {
      id: '/_app/devices/products/'
      path: '/'
      fullPath: '/devices/products/'
      preLoaderRoute: typeof AppDevicesProductsIndexRouteImport
      parentRoute: typeof AppDevicesProductsRoute
    }
    '/_app/devices/products/$id': {
      id: '/_app/devices/products/$id'
      path: '/$id'
      fullPath: '/devices/products/$id'
      preLoaderRoute: typeof AppDevicesProductsIdRouteImport
      parentRoute: typeof AppDevicesProductsRoute
    }
    '/_app/devices/list/': {
      id: '/_app/devices/list/'
      path: '/'
      fullPath: '/devices/list/'
      preLoaderRoute: typeof AppDevicesListIndexRouteImport
      parentRoute: typeof AppDevicesListRoute
    }
    '/_app/devices/list/$id': {
      id: '/_app/devices/list/$id'
      path: '/$id'
      fullPath: '/devices/list/$id'
      preLoaderRoute: typeof AppDevicesListIdRouteImport
      parentRoute: typeof AppDevicesListRoute
    }
  }
}

interface AppDevicesProductsRouteChildren {
  AppDevicesProductsIdRoute: typeof AppDevicesProductsIdRoute
  AppDevicesProductsIndexRoute: typeof AppDevicesProductsIndexRoute
}

const AppDevicesProductsRouteChildren: AppDevicesProductsRouteChildren = {
  AppDevicesProductsIdRoute: AppDevicesProductsIdRoute,
  AppDevicesProductsIndexRoute: AppDevicesProductsIndexRoute,
}

const AppDevicesProductsRouteWithChildren =
  AppDevicesProductsRoute._addFileChildren(AppDevicesProductsRouteChildren)

interface AppDevicesListRouteChildren {
  AppDevicesListIdRoute: typeof AppDevicesListIdRoute
  AppDevicesListIndexRoute: typeof AppDevicesListIndexRoute
}

const AppDevicesListRouteChildren: AppDevicesListRouteChildren = {
  AppDevicesListIdRoute: AppDevicesListIdRoute,
  AppDevicesListIndexRoute: AppDevicesListIndexRoute,
}

const AppDevicesListRouteWithChildren =
  AppDevicesListRoute._addFileChildren(AppDevicesListRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDevicesListRoute: typeof AppDevicesListRouteWithChildren
  AppDevicesProductsRoute: typeof AppDevicesProductsRouteWithChildren
  AppIngestComponentsRoute: typeof AppIngestComponentsRoute
  AppIngestGatewaysRoute: typeof AppIngestGatewaysRoute
  AppIngestProtocolsRoute: typeof AppIngestProtocolsRoute
  AppNotifConfigsRoute: typeof AppNotifConfigsRoute
  AppNotifTemplatesRoute: typeof AppNotifTemplatesRoute
  AppSystemOrgsRoute: typeof AppSystemOrgsRoute
  AppSystemRolesRoute: typeof AppSystemRolesRoute
  AppSystemUsersRoute: typeof AppSystemUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDevicesListRoute: AppDevicesListRouteWithChildren,
  AppDevicesProductsRoute: AppDevicesProductsRouteWithChildren,
  AppIngestComponentsRoute: AppIngestComponentsRoute,
  AppIngestGatewaysRoute: AppIngestGatewaysRoute,
  AppIngestProtocolsRoute: AppIngestProtocolsRoute,
  AppNotifConfigsRoute: AppNotifConfigsRoute,
  AppNotifTemplatesRoute: AppNotifTemplatesRoute,
  AppSystemOrgsRoute: AppSystemOrgsRoute,
  AppSystemRolesRoute: AppSystemRolesRoute,
  AppSystemUsersRoute: AppSystemUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
